<a href="https://colab.research.google.com/github/yms0606/SecuLayer/blob/main/%EC%8A%A4%EB%A7%88%ED%8A%B8%20%EA%B3%B5%EC%9E%A5%20%EC%A0%9C%ED%92%88%20%ED%92%88%EC%A7%88%20%EC%83%81%ED%83%9C%20%EB%B6%84%EB%A5%98%20AI%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%ED%95%B4%EC%BB%A4%ED%86%A4/%EC%8A%A4%EB%A7%88%ED%8A%B8_%EA%B3%B5%EC%9E%A5_%EC%A0%9C%ED%92%88_%ED%92%88%EC%A7%88_%EC%83%81%ED%83%9C_%EB%B6%84%EB%A5%98_AI_%EC%98%A8%EB%9D%BC%EC%9D%B8_%ED%95%B4%EC%BB%A4%ED%86%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [32]:
train_df = pd.read_csv('/content/drive/MyDrive/ML study/LG_SMART/train.csv')
test_df = pd.read_csv('/content/drive/MyDrive/ML study/LG_SMART/test.csv')

In [33]:
lines = ['T050304','T050307','T100304','T100306','T010306','T010305']

for line in lines:
  print(line,len(train_df[train_df['LINE']==line].drop(['PRODUCT_ID','Y_Class','Y_Quality','TIMESTAMP','LINE','PRODUCT_CODE'],axis=1).dropna(axis=1,how='all').columns))

T050304 1968
T050307 1975
T100304 671
T100306 671
T010306 886
T010305 886

In [7]:
train_df['LINE'].unique()

array(['T050304', 'T050307', 'T100304', 'T100306', 'T010306', 'T010305'],
      dtype=object)

In [21]:
test_df

    PRODUCT_ID         TIMESTAMP     LINE  ... X_2873  X_2874  X_2875
0     TEST_000   2022-09-09 2:01  T100306  ...    NaN     NaN     NaN
1     TEST_001   2022-09-09 2:09  T100304  ...    NaN     NaN     NaN
2     TEST_002   2022-09-09 8:42  T100304  ...    NaN     NaN     NaN
3     TEST_003  2022-09-09 10:56  T010305  ...    NaN     NaN     NaN
4     TEST_004  2022-09-09 11:04  T010306  ...    NaN     NaN     NaN
..         ...               ...      ...  ...    ...     ...     ...
305   TEST_305  2022-11-05 11:18  T100306  ...    NaN     NaN     NaN
306   TEST_306  2022-11-05 16:39  T100304  ...    NaN     NaN     NaN
307   TEST_307  2022-11-05 16:47  T100306  ...    NaN     NaN     NaN
308   TEST_308  2022-11-05 20:53  T100306  ...    NaN     NaN     NaN
309   TEST_309  2022-11-05 21:01  T100306  ...    NaN     NaN     NaN

[310 rows x 2879 columns]

In [34]:
line1 = ['T050304','T050307']
line2 = ['T100304','T100306']
line3 = ['T010306','T010305']

line1_df = train_df[train_df['LINE'].isin(line1)]
line2_df = train_df[train_df['LINE'].isin(line2)]
line3_df = train_df[train_df['LINE'].isin(line3)]

In [35]:
line1_df = line1_df.drop(['PRODUCT_ID','Y_Quality','TIMESTAMP','LINE','PRODUCT_CODE'],axis=1)
line2_df = line2_df.drop(['PRODUCT_ID','Y_Quality','TIMESTAMP','LINE','PRODUCT_CODE'],axis=1)
line3_df = line3_df.drop(['PRODUCT_ID','Y_Quality','TIMESTAMP','LINE','PRODUCT_CODE'],axis=1)

In [40]:
line1_df = line1_df.fillna(0)
line2_df = line2_df.fillna(0)
line3_df = line3_df.fillna(0)

line1_df_x = line1_df.drop(['Y_Class'],axis=1)
line2_df_x = line2_df.drop(['Y_Class'],axis=1)
line3_df_x = line3_df.drop(['Y_Class'],axis=1)

In [ ]:
!pip install catboost

In [44]:
#from catboost import CatBoostClassifier

In [47]:
#model = CatBoostClassifier(iterations=9053,learning_rate=0.6, reg_lambda=17,
#                           depth=2, min_data_in_leaf=4, leaf_estimation_iterations=4)

In [ ]:
#model.fit(line1_df_x,line1_df['Y_Class'])
#model.fit(line2_df_x,line2_df['Y_Class'])
#model.fit(line3_df_x,line3_df['Y_Class'])

In [51]:
#test_df = test_df.drop(['PRODUCT_ID','TIMESTAMP','LINE','PRODUCT_CODE'],axis=1)
#pred = model.predict(test_df)

In [ ]:
#pred

In [41]:
model1 = LGBMClassifier(n_estimators=400)
model1.fit(line1_df_x,line1_df['Y_Class'])

model2 = XGBClassifier()
model2.fit(line2_df_x,line2_df['Y_Class'])

model3 = RandomForestClassifier()
model3.fit(line3_df_x,line3_df['Y_Class'])

RandomForestClassifier()

In [49]:
Y_LABEL = []

def predict_model(dfs):
  for i in range(len(dfs)):
    if dfs.iloc[i]['LINE'] in line1:
      df = dfs.iloc[i].drop(['PRODUCT_ID','TIMESTAMP','LINE','PRODUCT_CODE'])
      df = df.fillna(0)
      df = pd.DataFrame(df)
      df = df.transpose()
      preds = model.predict(df)
      Y_LABEL.append(preds[0])
    elif dfs.iloc[i]['LINE'] in line2:
      df = dfs.iloc[i].drop(['PRODUCT_ID','TIMESTAMP','LINE','PRODUCT_CODE'])
      df = df.fillna(0)
      df = pd.DataFrame(df)
      df = df.transpose()
      preds = model.predict(df)
      Y_LABEL.append(preds[0])
    elif dfs.iloc[i]['LINE'] in line3:
      df = dfs.iloc[i].drop(['PRODUCT_ID','TIMESTAMP','LINE','PRODUCT_CODE'])
      df = df.fillna(0)
      df = pd.DataFrame(df)
      df = df.transpose()
      preds = model.predict(df)
      Y_LABEL.append(preds[0])

In [30]:
predict_model(test_df)

In [53]:
submit = pd.read_csv('/content/drive/MyDrive/ML study/LG_SMART/sample_submission.csv')
submit['Y_Class'] = pred
submit.to_csv('submit1.csv',index=False)